### ISSUE TITLE
Not all kudos are saved in the kudo box 

### ISSUE THREAD

**Issue by henrypratsch** [falcowinkler/kudo-box#28]
Hello 👋 ,
We noticed some issues with the kudo box recently. It seems like when many people type in kudos at the same time, the kudo box is not filled properly with all of the kudos.

Also when opening the kudo box a second time shortly after, a lot of kudos that were loaded, seem to be duplicated from previous kudo boxes.

**Comment by falcowinkler** [comment]
Thanks @henrypratsch, will look into this :)

**Comment by falcowinkler** [comment]
@henrypratsch 
As for the first issue, unfortunately i cannot reproduce it. Please reopen if it happens again or ping me, and i can inspect the logs. multiple people writing kudos shouldn't be an issue, maybe it was another mistake or bug.

As for the second problem, i think what happened is that the first "open-kudo-box" command wasn't finished uploading the kudos yet, and then another open-kudo-box command was run, thus rendering kudos twice.

To prevent this i have implemented a check to see if a kudo box is currently opened. If this is the case, you will receive an error, and you have to proceed once the first "open kudo box" is finished.

<img width="580" alt="Screenshot 2024-05-24 at 23 26 06" src="https://github.com/falcowinkler/kudo-box/assets/8613031/b6388a7f-b63c-43c1-8ce6-c3f85afbb657">
